# Generated by Django 2.1.3 on 2019-02-01 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タスク')),
                ('detail', models.TextField(verbose_name='詳細')),
                ('deadline', models.DateTimeField(verbose_name='期日')),
                ('staff', models.TextField(verbose_name='担当者')),
                ('remarks', models.CharField(max_length=50, verbose_name='備考')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 2, 1, 10, 43, 59, 519258), verbose_name='作成び')),
            ],
        ),
    ]
