# Generated by Django 2.1.3 on 2019-02-01 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20190201_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 11, 16, 38, 527642), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='タスク名'),
        ),
    ]
