# Generated by Django 2.1.3 on 2019-02-01 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20190201_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 11, 28, 34, 502848), verbose_name='作成日'),
        ),
    ]
